config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get 'home', to: 'home#index'
  get 'reactt', to: 'home#reacttutorial'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  resources :users, only:[:index, :show, :destroy]
  resources :comments, only:[:new, :create, :destroy]
  resources :posts
  resources :likeposts, only: [:create, :destroy]

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments,  dependent: :destroy
  has_many :likeposts, dependent: :destroy
  validates :user_id,     presence: true
  validates :title,      length: {maximum: 99}
  validates :content,    length: {maximum: 1024}, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
    @comment = Comment.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    redirect_to posts_path
  end

  private

    def post_params
      params.require(:post).permit( :title, :content, :public)
    end

    def correct_user
      post = Post.find(params[:id])
      if post.user_id != current_user.id
        redirect_to '/posts'
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.haml
= form_for @post, remoto: false  do |f|
  .form_item
    = f.label :title
    = f.text_field :title
  .form_item
    = f.label :content
    = f.text_area :content
  .form_item
    = f.label :public
    = f.check_box :public
  .form_item
    = f.submit

app/views/posts/index.html.haml
%h1 Posts#index
= link_to "newしちゃう？", new_post_path
.post
  - @posts.each do |post|
    .post_item
      .post_title
        = link_to post.title, post_path(post)
        .post_edit
          - if !post.public
            xx非公開xx
          - if has_authority?(post)
            = link_to "", edit_post_path(post), class: "fas fa-edit"
            = link_to "", post_path(post), method: :delete, class: "fas fa-trash"
        .post_owner
          = link_to post.user.nickname, user_path(post.user)
      .post_content
        = simple_format post.content
      .post_like
        = "#{post.likeposts.count} いいねされてる"
        = link_to "いいねする", likeposts_path(post_id: post.id), method: :post
        = link_to "いいね消す", likepost_path(post.id), method: :delete
      .post_date
        = post.updated_at.strftime("%Y/%m/%d %H:%M:%S")
      .comments
        .comments_head
          - if post.comments.present?
            = "コメント一覧"
          - else
            = "コメントはありません"
        .comments_body
          %ul
            - post.comments.each do |comment|
              %li
                = comment.user.nickname
                = ":"
                = comment.content
                .post_date
                  - if has_authority?(comment)
                    = link_to "", comment_path(comment), method: :delete, class: "fas fa-trash"
                  = comment.updated_at.strftime("%Y/%m/%d %H:%M:%S")
          = form_for @comment, remoto: false  do |f|
            = render 'shared/error_messages', object: f.object
            = f.hidden_field :post_id, value: post.id
            .form_item
              = f.label :content
              = f.text_area :content
            .form_item
              = f.submit

app/views/posts/new.html.haml
= form_for @post, remoto: false  do |f|
  = render 'shared/error_messages', object: f.object
  .form_item
    = f.label :title
    = f.text_field :title
  .form_item
    = f.label :content
    = f.text_area :content
  .form_item
    = f.label :public
    = f.check_box :public
  .form_item
    = f.submit

app/views/posts/show.html.haml
.post_item
  .post_title
    = @post.title
    .post_edit
      - if !@post.public
        xx非公開xx
      = link_to "●", edit_post_path(@post)
      = link_to "罰", post_path(@post), method: :delete
  .post_content
    = @post.content
    = @post.updated_at
    = @post.created_at
= link_to "戻る", :back